import { deriveNameFromEmail, looksLikePhone } from "@/lib/leads/contactFields";
import { prisma } from "@/lib/prisma";
import { toPlainLine } from "@/lib/text/plainText";
import { CONTACT_LIMITS, normaliseEmail } from "@/lib/validation/contactSchemas";
import type { ImportFieldKey } from "@/lib/leads/spreadsheet";

/** What will happen to one row once the import is committed. */
export type RowOutcome =
  /** Email not seen before — a new contact. */
  | "create"
  /** Email already in the database. The operator picks what to do about it. */
  | "match"
  /** Same email appeared earlier in this same file. First occurrence wins. */
  | "duplicate-in-file"
  /** Unusable — no email, or one that isn't an address. */
  | "invalid";

/** What to do with a row whose email already exists. Chosen per row in the preview. */
export type MatchAction =
  /** Log the touchpoint and fill only fields that are currently empty. */
  | "enrich"
  /** Log the touchpoint and change nothing on the existing record. */
  | "log"
  /** Log it and overwrite name/company/phone with the spreadsheet's values. */
  | "overwrite"
  /** Do nothing at all — not even a history entry. */
  | "skip";

export const DEFAULT_MATCH_ACTION: MatchAction = "enrich";

export interface PlannedRow {
  /** 1-based row number in the original file, header excluded — so it matches what Excel shows. */
  rowNumber: number;
  outcome: RowOutcome;
  name: string;
  email: string;
  company: string | null;
  phone: string | null;
  message: string | null;
  /** Why the row is invalid, or which row it duplicates. */
  reason: string | null;
  /** Non-fatal notes — the row still imports, but something was adjusted or dropped. */
  warnings: string[];
  /** Set when `outcome` is "match". */
  existingContactId: string | null;
  existingSummary: string | null;
}

export interface ImportPlan {
  rows: PlannedRow[];
  counts: Record<RowOutcome, number>;
}

const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

function readCell(row: string[], columnIndex: number | null): string {
  if (columnIndex === null || columnIndex < 0) {
    return "";
  }

  return toPlainLine(row[columnIndex] ?? "");
}

function truncate(value: string, max: number): string {
  return value.length > max ? value.slice(0, max) : value;
}

/**
 * Works out, without writing anything, what committing this file would do.
 *
 * Everything the preview shows comes from here, so the screen an operator confirms is
 * generated by the same code that later performs the work — the preview cannot drift from
 * the outcome the way a separately-written summary would.
 */
export async function buildImportPlan(
  rows: string[][],
  mapping: Record<ImportFieldKey, number | null>,
): Promise<ImportPlan> {
  const planned: PlannedRow[] = [];
  // Tracks emails already seen in THIS file, so the second occurrence can point at the first.
  const seenInFile = new Map<string, number>();

  const candidates: { rowNumber: number; email: string }[] = [];

  for (const [index, row] of rows.entries()) {
    const rowNumber = index + 1;
    const rawEmail = readCell(row, mapping.email);
    const email = normaliseEmail(rawEmail);
    const name = truncate(readCell(row, mapping.name), CONTACT_LIMITS.name);
    const company = truncate(readCell(row, mapping.company), CONTACT_LIMITS.company);
    const phone = truncate(readCell(row, mapping.phone), CONTACT_LIMITS.phone);
    const message = truncate(readCell(row, mapping.message), CONTACT_LIMITS.message);

    // A blank name becomes a readable guess from the address rather than the raw address —
    // "Julia Roberts", not "julia.roberts@corp.com" sitting in the panel as a person's name.
    const resolvedName = name || (email ? deriveNameFromEmail(email) : "");

    // Keep the number exactly as typed for display, but drop values with no plausible digits
    // in them ("ABC12345") instead of storing nonsense a salesperson would try to dial.
    const usablePhone = phone && looksLikePhone(phone) ? phone : null;

    const base = {
      rowNumber,
      name: resolvedName,
      email,
      company: company || null,
      phone: usablePhone,
      message: message || null,
      existingContactId: null,
      existingSummary: null,
      warnings: [] as string[],
    };

    if (phone && !usablePhone) {
      base.warnings.push(`"${phone}" doesn't look like a phone number — it won't be saved.`);
    }
    if (!name && email) {
      base.warnings.push(`No name column value — guessed "${resolvedName}" from the email.`);
    }

    if (!email) {
      planned.push({ ...base, outcome: "invalid", reason: "No email address." });
      continue;
    }

    if (!EMAIL_PATTERN.test(email) || email.length > CONTACT_LIMITS.email) {
      planned.push({ ...base, outcome: "invalid", reason: `"${rawEmail}" isn't an email address.` });
      continue;
    }

    const firstSeenAt = seenInFile.get(email);

    if (firstSeenAt !== undefined) {
      planned.push({
        ...base,
        outcome: "duplicate-in-file",
        reason: `Same email as row ${firstSeenAt}. The first one wins.`,
      });
      continue;
    }

    seenInFile.set(email, rowNumber);
    candidates.push({ rowNumber, email });
    planned.push({ ...base, outcome: "create", reason: null });
  }

  // One query for the whole file rather than one per row — a 5,000-row import would otherwise
  // open 5,000 round trips to Supabase.
  const existingContacts = await prisma.contact.findMany({
    where: { email: { in: candidates.map((candidate) => candidate.email) } },
    select: {
      id: true,
      email: true,
      name: true,
      company: true,
      phone: true,
      status: true,
      assignedTo: { select: { name: true } },
    },
  });

  const existingByEmail = new Map(existingContacts.map((contact) => [contact.email, contact]));

  for (const row of planned) {
    if (row.outcome !== "create") {
      continue;
    }

    const existing = existingByEmail.get(row.email);

    if (existing) {
      row.outcome = "match";
      row.existingContactId = existing.id;
      row.existingSummary = [
        existing.name,
        existing.company,
        existing.assignedTo ? `owned by ${existing.assignedTo.name}` : "unassigned",
        existing.status.toLowerCase(),
      ]
        .filter(Boolean)
        .join(" · ");
    }
  }

  const counts: Record<RowOutcome, number> = {
    create: 0,
    match: 0,
    "duplicate-in-file": 0,
    invalid: 0,
  };

  for (const row of planned) {
    counts[row.outcome] += 1;
  }

  return { rows: planned, counts };
}
